name: codelab_training
description: "Trainig app to develope the entire tutorial list from flutter.dev"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  go_router: ^14.2.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
